import type { Metadata } from "next";
import { figtree, maisonNeue } from "@/lib/font/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${maisonNeue.variable} ${figtree.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
